# 应用名称
spring:
  application:
    name: practice

  datasource:
    # 配置数据源类型
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/practice?useUnicode=true&characterEncoding=UTF-8&userSSL=false&serverTimezone=GMT%2B8
    username: root
    password: harry123
    #初始化最小，最大连接数
    initialSize: 3
    minidle: 3
    maxActive: 18
    #获取数据库连接等待的超时时间
    maxWait: 60000
    # 配置多久进行一次检测，检测需要关闭的空闲连接，单位毫秒
    timeBetweenEvictionRunsMills: 60000
    validationQuery: SELECT 1 FROM dual
    #配置监控统计拦截的filters，去掉后，监控界面的sql无法统计
    filters: stat,wall,log4j

# 应用服务 WEB 访问端口
server:
  servlet:
#      context-path: /practice  #设置项目contextpath
      context-path: /  #设置项目contextpath
  port: 8080 #设置tomcat端口
  tomcat:
    uri-encoding: utf-8 #设置tomcat编码

# mybatis配置
mybatis:
  #配置映射类所在包名
  type-aliases-package: com.harry.practice.entity
  #配置mapper xml文件所在路径，这里是一个数组
  mapper-locations: classpath:mapper/*.xml


